---
title: "Owner Analysis"
author: "Lena Capecee"
date: "2023-04-05"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)

```

## read in data

```{r}

lobster_abundance <- read_csv("../data/Lobster_Abundance_All_Years_20220829.csv")

```
## convert data and remove NA 

```{r}
lobster_abundance <- lobster_abundance %>% 
    mutate(SIZE_MM = na_if(SIZE_MM, -99999))

```

## Exercise: Data Visualization

### Question 7

```{r}

ggplot(data=lobster_abundance, aes(x=SIZE_MM)) +
  geom_histogram() +
  facet_wrap(~SITE)

```
### Question 8

```{r}

lobsters_summarize <- lobster_abundance %>% 
  group_by(SITE,YEAR) %>% 
  summarize(COUNT = n())

ggplot(data=lobsters_summarize, aes(x=YEAR, y=COUNT, color=SITE)) +
  geom_line() +
  geom_point()

```


### Question 9 

```{r}

lobster_size_lrg <- lobster_abundance %>% 
  filter(YEAR %in% c(2019,2020,2021)) %>% 
  mutate(SIZE_BIN = if_else(SIZE_MM <= 70, true = "small", false = "large")) %>% 
  group_by(SITE,SIZE_BIN) %>% 
  summarize(COUNT = n()) %>%
  drop_na()

unique(lobster_size_lrg$SIZE_BIN)
  

lobster_size_site<-ggplot(data=lobster_size_lrg, aes(x=SITE, y=COUNT, fill=SIZE_BIN)) +
  geom_col(position="dodge")

ggsave("../figs/lobster_size_site.png", lobster_size_site)

```

